channel:
  prod: 
  # stage: 
  # dev: 
max_message_length: 2000
new:
  hours: 72
  emoji: new
  description: fil créé dans les 3 derniers jours
up:
  hours: 24
  emoji: up
  description: fil réactivé dans les dernières 24 heures
dying:
  hours: 12
  emoji: hourglass
  description: fil risquant l'archivage dans les 12 heures
